#GENERATED BY ChatGPT
def multiple(arr)
  result = 1                #初期化,0にすると結果が0になる
  arr.each do |num|
    result *= num           #result = result * num
  end 
  return result 
end 

array = [1, 3, 5, 7, 9]
puts multiple(array)